site_name: GraphChem Documentation
nav:
  - Installation: index.md
  - API Documentation:
    - graphchem.data: api_data.md
    - graphchem.datasets: api_datasets.md
    - graphchem.nn: api_nn.md
    - graphchem.preprocessing: api_preprocessing.md
theme: material
plugins:
  - search
  - mkdocstrings
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js